### ISSUE TITLE
Nuxt: btoa is not defined

### ISSUE THREAD

**Issue by Giacomo92** [juliandreas/vue-toggles#4]
I have this error when I try to add **vue-toggles** component to my project:
<img width="1865" alt="Schermata 2020-07-13 alle 12 34 00" src="https://user-images.githubusercontent.com/11694429/87295316-4b79c000-c505-11ea-86b4-683bbdac747a.png">

How can I solve this?

**Comment by juliandreas** [comment]
I don't think this is an issue to do with **vue-toggles**. And if it was, I can't help you without knowing your setup or how you tried to install it.

Here is a sample with the package installed on a clean Vue project: https://codesandbox.io/s/vue-toggles-mkkp4?file=/src/App.vue

If you still need help, please give me a codesandbox to help me debug your issue.

**Comment by Giacomo92** [comment]
I have added this package in a Nuxt project. The "btoa error" comes up only if I try to add vue-toggles component and only after the server starts up.

This is the codesandbox:
https://codesandbox.io/s/condescending-river-ei7te?file=/plugins/vue-toggles.js

Thank you for your support @juliandreas

**Comment by juliandreas** [comment]
This seem to be a Nuxt-only error. I will look into it asap.

Thanks for bringing this to my attention.

**Comment by juliandreas** [comment]
@Giacomo92 
I think I have solved the issue, will you help me test it?

You can install the beta with the command `npm i vue-toggles@beta` and see if it runs for you after your project is started.

If you give me a green light I will publish the fix to the main branch.

**Comment by Giacomo92** [comment]
The error still persists. I cannot understand which of yours lines of codes generates the bugged function `addStyle()` in the **vue-toogles.umd.js** file.
I have also updated the codesandbox [here](https://codesandbox.io/s/condescending-river-ei7te?file=/plugins/vue-toggles.js) and I find [this](https://github.com/vuejs/vue-component-compiler/issues/88) related issue

**Comment by juliandreas** [comment]
I thought I fixed it with changing `background` to `backgroundColor` in the added style-attributes, but now when I try it again it doesn't work like you said.

It's super hard to bugfix this when you have no idea what the issue is. I'll let you know if there's progress.

**Comment by Giacomo92** [comment]
I have isolated the error. This bug is caused by style tag. If you temporarily remove the style tag in the vue component it is working!
Can we add the style instructions as a detached file?

**Comment by juliandreas** [comment]
Don't you think the problem is the generated code which gets sent to the style-tag, rather than the style-tag itself?

Maybe we can isolate it even further. Did you remove all the style-tags or from just one element?

**Comment by Giacomo92** [comment]
`<style lang="scss">
/*no code here*/
</style>` ---> bug still persist

if I remove all the block code listed up here, it's working fine!

**Comment by juliandreas** [comment]
I think you're on to something. I won't have time to look into this more until the weekend though.

**Comment by Giacomo92** [comment]
I think **rollup** does not support SSR, i see that other components use webpack like [this](https://github.com/lokyoung/vuejs-paginate/blob/master/package.json) or [this](https://github.com/sagalbot/vue-select) . Can I ask you why you choose rollup instead webpack?

**Comment by juliandreas** [comment]
It's what's demonstrated in the [vue docs](https://vuejs.org/v2/cookbook/packaging-sfc-for-npm.html)

One solution might be using the `.vue` file directly. The only downside is that you can't use the package via the `<script>`-tag and I can live with that.

**Comment by juliandreas** [comment]
I found other libraries solution to issues like this is installing it in `nuxt.config.js` with a `mode: client` (previously "ssr: false") option:

`
plugins: [
    {
      src: "~plugins/vue-toggles.js",
      mode: "client"
    }
  ]
`
[Plugins property](https://nuxtjs.org/api/configuration-plugins/)

And the `VueToggles`-component should be wrapped with `<client-only>` (previously no-ssr)
[client-only](https://nuxtjs.org/api/components-client-only/)

**Comment by juliandreas** [comment]
I will now close this issue since we have a viable solution for it.

The package is updated with instructions on how to install it properly on Nuxt.

**Comment by juliandreas** [comment]
I have now added full SSR support so you don't have to deal with stuff like `mode: client` and `<client-only>`.

You just need a different import for SSR:
```
import Vue from 'vue';
import VueToggles from 'vue-toggles/dist/vue-toggles.ssr';
import 'vue-toggles/dist/vue-toggles.ssr.css';

Vue.component('VueToggles', VueToggles);
```
